# Generated by Django 5.2.7 on 2025-11-05 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('custom_id', models.CharField(max_length=10, unique=True)),
                ('category', models.TextField()),
                ('location', models.CharField()),
                ('certifications_required', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('specifications', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the schedule (e.g., 'Fall 2024 Hours', 'Summer Break Schedule')", max_length=120)),
                ('start_date', models.DateField(help_text='The date when this schedule becomes active')),
                ('end_date', models.DateField(help_text='The date when this schedule ends')),
                ('open_time', models.TimeField(help_text='Daily opening time')),
                ('close_time', models.TimeField(help_text='Daily closing time')),
                ('days_of_week', models.CharField(help_text='Days this schedule applies to (stored as comma-separated values: Mon,Tue,Wed,Thu,Fri,Sat,Sun)', max_length=50)),
                ('location', models.CharField(blank=True, help_text='Location where this schedule applies', max_length=100, null=True)),
                ('holidays', models.TextField(blank=True, help_text="Holiday dates in mm-dd-yr format, separated by semicolons (e.g., '12-25-24;01-01-25')", null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Whether this is the currently active schedule')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('custom_id', models.CharField(max_length=10, unique=True)),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(choices=[('2nd Floor: Hatch Front', '2nd Floor: Hatch Front'), ('2nd Floor: Hatch Back', '2nd Floor: Hatch Back'), ('3rd Floor: Prototyping Studio', '3rd Floor: Prototyping Studio'), ('3rd Floor: Prototyping Shop', '3rd Floor: Prototyping Shop')])),
                ('floor', models.IntegerField(choices=[(2, '2nd Floor'), (3, '3rd Floor')])),
                ('type', models.CharField(choices=[('table', 'Table Workstation'), ('classroom', 'Classroom Space')])),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservable_type', models.CharField(choices=[('space', 'Space'), ('machine', 'Machine'), ('trainer', 'Trainer')], help_text="Choose what you're booking", max_length=20)),
                ('reservation_title', models.CharField(max_length=120)),
                ('reservable_custom_id', models.CharField(help_text='The custom ID of the space, machine, or trainer being reserved.', max_length=10)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['reservable_type', 'reservable_custom_id', 'start_time', 'end_time'], name='cmr_reserva_reserva_c45105_idx')],
            },
        ),
    ]
