# Generated by Django 5.2.7 on 2025-11-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='floorplan_image',
            field=models.ImageField(blank=True, help_text="Upload an image showing the space's location on the floor plan.", null=True, upload_to='floorplans/'),
        ),
    ]
