# Generated by Django 5.2.7 on 2025-11-09 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmr', '0002_space_floorplan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='type',
            field=models.CharField(choices=[('station', 'Table Workstation'), ('classroom', 'Classroom Space')]),
        ),
        migrations.CreateModel(
            name='SpaceCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(choices=[('Laser', 'Laser'), ('Vinyl', 'Vinyl'), ('Woodworking', 'Woodworking'), ('Textile', 'Textile'), ('Metalworking', 'Metalworking'), ('3D Printing', '3D Printing'), ('Electronics', 'Electronics')], max_length=100)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='cmr.space')),
            ],
            options={
                'unique_together': {('space', 'machine_type')},
            },
        ),
    ]
