# Generated by Django 5.2.7 on 2025-11-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmr', '0002_space_floorplan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='space_id',
            field=models.CharField(default='unassigned'),
        ),
    ]
