# Generated by Django 5.2.7 on 2025-11-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmr', '0003_machine_space_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='space_id',
            field=models.CharField(default='unassigned', max_length=130),
        ),
    ]
