# Generated by Django 5.2.7 on 2025-11-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmr', '0004_alter_machine_space_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='space_id',
            field=models.CharField(blank=True, default='unassigned', max_length=130, null=True),
        ),
    ]
