# Generated by Django 5.2.7 on 2025-11-07 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmr', '0005_alter_machine_space_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='location',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='cmr.machine')),
            ],
        ),
    ]
