# Generated by Django 5.2.7 on 2025-11-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmr', '0006_remove_machine_location_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machine_image',
            field=models.ImageField(blank=True, help_text='Upload an image of the machine', null=True, upload_to='machines/'),
        ),
    ]
