# Generated by Django 5.2.7 on 2025-11-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmr', '0007_machine_machine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_image',
            field=models.ImageField(blank=True, null=True, upload_to='machines/'),
        ),
    ]
