# Generated by Django 5.2.7 on 2025-11-09 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmr', '0003_alter_space_type_spacecapability'),
        ('cmr', '0008_alter_machine_machine_image'),
    ]

    operations = [
    ]
