# Generated by Django 5.2.7 on 2025-11-10 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmr', '0009_merge_20251109_2243'),
        ('cmr', '0009_merge_20251109_2309'),
    ]

    operations = [
    ]
