# Generated by Django 5.2.7 on 2025-11-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmr", "0010_merge_20251110_0106"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=130)),
                ("custom_id", models.CharField(max_length=10, unique=True)),
                ("major", models.TextField(blank=True, max_length=200)),
                ("training_certificates", models.TextField(blank=True, null=True)),
                (
                    "trainer_image",
                    models.ImageField(blank=True, null=True, upload_to="trainers/"),
                ),
            ],
        ),
    ]
