# Generated by Django 5.2.7 on 2025-11-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmr', '0010_merge_20251110_0057'),
        ('cmr', '0011_trainer'),
    ]

    operations = [
    ]
