# Generated by Django 5.2.7 on 2025-11-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmr', '0012_merge_0010_merge_20251110_0057_0011_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='about',
            field=models.TextField(blank=True, default='None', null=True),
        ),
    ]
