# Generated by Django 5.2.7 on 2025-11-18 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmr', '0013_machine_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='capabilities',
            field=models.ManyToManyField(blank=True, help_text='Which machines this space is capable of hosting.', related_name='supported_by_spaces', to='cmr.machine'),
        ),
        migrations.AddField(
            model_name='space',
            name='current_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_in_spaces', to='cmr.machine'),
        ),
        migrations.DeleteModel(
            name='SpaceCapability',
        ),
    ]
