# Generated by Django 5.2.7 on 2025-11-18 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmr', '0014_space_capabilities_space_current_machine_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reservation',
            name='cmr_reserva_reserva_c45105_idx',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservable_custom_id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservable_type',
        ),
        migrations.AddField(
            model_name='machine',
            name='installed_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_installed_here', to='cmr.space'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='linked_reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverse_link', to='cmr.reservation'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_reservations', to='cmr.machine'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_reservations', to='cmr.space'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_reservations', to='cmr.trainer'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['date', 'start_time', 'end_time'], name='cmr_reserva_date_bb41da_idx'),
        ),
    ]
