# Generated by Django 5.2.7 on 2025-11-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmr', '0015_remove_reservation_cmr_reserva_reserva_c45105_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='certified_machines',
            field=models.ManyToManyField(blank=True, help_text='Machines this trainer is certified to supervise', related_name='certified_trainers', to='cmr.machine'),
        ),
    ]
