# Generated by Django 5.2.7 on 2025-11-20 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmr', '0016_trainer_certified_machines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='space_id',
        ),
    ]
