# Generated by Django 5.2.7 on 2025-12-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmr', '0017_remove_machine_space_id'),
        ('pct', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='certifications_required',
        ),
        migrations.AddField(
            model_name='machine',
            name='certifications_required',
            field=models.ManyToManyField(blank=True, help_text='Training courses required to operate this machine.', related_name='machines_requiring', to='pct.trainingcourse'),
        ),
    ]
