# Generated by Django 5.2.7 on 2025-12-02 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmr', '0018_remove_machine_certifications_required_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]

# Generated by Django 5.2.7 on 2025-12-02 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmr', '0018_remove_machine_certifications_required_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
