# Generated by Django 5.2.7 on 2025-12-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmr', '0019_delete_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', help_text='Approval status for trainer reservations', max_length=20),
        ),
    ]
