# Generated by Django 5.2.7 on 2025-12-04 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmr', '0020_reservation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Brief subject of the help request', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the issue or request')),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', help_text='Current status of the ticket', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the ticket was created')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the ticket was resolved', null=True)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Admin who resolved the ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_tickets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who submitted the ticket', on_delete=django.db.models.deletion.CASCADE, related_name='help_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
