# Generated by Django 5.2.7 on 2025-12-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmr', '0021_helpticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpticket',
            name='category',
            field=models.CharField(choices=[('website', 'Website'), ('machine', 'Machine'), ('spaces', 'Spaces'), ('training', 'Training')], default='website', help_text='Category of the issue', max_length=20),
        ),
    ]
