# Generated by Django 5.2.7 on 2025-12-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmr', '0022_helpticket_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the contact', max_length=200)),
                ('position', models.CharField(help_text='Job title or position', max_length=200)),
                ('email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('photo', models.ImageField(blank=True, help_text='Profile photo (optional)', null=True, upload_to='contacts/')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
