# Generated by Django 5.2.7 on 2025-12-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmr', '0023_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event title', max_length=200)),
                ('description', models.TextField(help_text='Event description')),
                ('event_date', models.DateField(help_text='Date of the event')),
                ('event_time', models.TimeField(help_text='Time of the event')),
                ('location', models.CharField(help_text='Event location', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Event image (optional)', null=True, upload_to='events/')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
            ],
            options={
                'ordering': ['event_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project title', max_length=200)),
                ('description', models.TextField(help_text='Project description')),
                ('student_name', models.CharField(help_text='Name of student(s) who worked on this project', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Project image (optional)', null=True, upload_to='projects/')),
                ('date_completed', models.DateField(help_text='Date project was completed')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
            ],
            options={
                'ordering': ['-date_completed', 'order'],
            },
        ),
    ]
